[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
[compat]
julia = "1.3"
PyCall = "1.90"
PyPlot = "2"
